### ISSUE TITLE
Unable to add settings url

### ISSUE THREAD

**Issue by hitchhiker** [myfreeweb/transmitter#11]
I've tried a few methods, latest FF Quantum.. I'm unable to add my server URL, it simply freezes on the UI settings page.

**Comment by valpackett** [comment]
That's weird. What exactly freezes? The whole browser? Settings tab?

**Comment by hitchhiker** [comment]
.. the actual settings HTML UI .. or more specifically the INPUTs are unresponsive.. 
1) I enter the IP of my transmission server into 'SERVER URL'.. (actually any IP seems to do it)
2) Click over any [INPUT] below that, and it's all unresponsive.. ie won't set focus etc. / SAVE button doesn't click / [SELECT] doesn't respond etc etc - however the checkboxes (auto update) above do work.

**Comment by valpackett** [comment]
Are you entering the URL correctly? (Should end in `/transmission/` as the label says). If it's not correct, it should show an alert, but looks like alerts don't actually show up. (Showed up for me in development o_0)

**Comment by hitchhiker** [comment]
I wasn't - my bad, read it as 'without transmission/web/rpc' :( oops. Works now - cheers!

**Comment by valpackett** [comment]
Yeah, I should fix this to use something other than `alert()`…
