### ISSUE TITLE
Problem with non standard URL

### ISSUE THREAD

**Issue by ghost** [myfreeweb/transmitter#12]
Hi,

I have a custom URL for transmission ( /t/ instead of /transmission/) and am getting UI freezes when I try to save. I can save if I enter the /transmission/ URL.

**Comment by ghost** [comment]
This code

	if (!data.base_url.endsWith('/transmission/')) {
		alert('WARNING: Server URL does not end with /transmission/ — make sure it is actually correct!')
}

Should be replaced with a communications check and error displayed below where the "save success" is displayed. I don't get an alert btw.

Thanks

**Comment by valpackett** [comment]
Released version 1.1.1, the warning is now on the page.
