### ISSUE TITLE
Ability to use a port different then 9091 

### ISSUE THREAD

**Issue by kaneda79** [myfreeweb/transmitter#16]
Hi,
first of all thanks for your work.
I use Transmission on a port different then the standard Transmission port. When i write that port in the Server URL, Transmitter gives me this error: "Error. SyntaxError. JSON.parse: unexpected character at line 1 column 1 of teh JSON data".
I am not even sure the problem is with Transmitter, but if i use the standard port the message doesn't show.
Any suggestion?

Thanks in advance
kaneda79

**Comment by valpackett** [comment]
Hi.

I use Transmission behind a TLS reverse proxy on port 443. Port shouldn't matter at all.

What exact URL are you setting?

**Comment by kaneda79** [comment]
http://<ip address>:<port>/Transmision/
When I press on the Transmitter Icon (i mean the one before the gear) It's able to open a new Tab pointing to Transmission (and asking me login and password) but i am no able to add the desired magnet through the "Download with transmission Remote" option in the menu.
I didn't mension this is happening on Firefox. Well as soon as possible i'll try with another PC too, just to be sure is not me causing the problem.

**Comment by valpackett** [comment]
`Transmision` instead of `transmission` would be bad ;)

You should login on that page! Transmitter needs you to use the web UI at least once, to get an active session.

**Comment by kaneda79** [comment]
Thanks a lot! 
first of all sorry for the late answer. You was right, the problem was the capital letter even if my directory (and settings.json option) is like that. i thought it is case sensitive, but i was mistaken.
Thanks again!
