### ISSUE TITLE
Feature request- switch the types of icon badge automatically

### ISSUE THREAD

**Issue by izackwu** [myfreeweb/transmitter#19]
Hello~ Thank you for developing this awesome add-on.

Is it possible to switch the types of icon badge automatically? For example, when I'm downloading somethings, it will display the download speed; and if I have finished downloading, it will switch automatically to upload speed.
Or to make things easier, let's simply switch it every refresh regardless of the status of downloading?
I think this feature will be quite useful ( as far as I'm concerned).

**Comment by valpackett** [comment]
Thanks!

This shouldn't be too hard, yeah...
