### ISSUE TITLE
"Error undefined"

### ISSUE THREAD

**Issue by FoxBJK** [myfreeweb/transmitter#2]
That's all I get. The extension doesn't seem to work otherwise. Is there a log somewhere? My Transmission instance is up and running, and Firefox sees it just fine, not sure what the cause is.

**Comment by FoxBJK** [comment]
Turns out "/transmission/" is require don the URL or the check will fail. Would be helpful if that was explained better in errors or the setup UI, but it seems to work now

**Comment by valpackett** [comment]
Yeah, the error message is bad :D But I think it's pretty clear in the setup UI:

<img width="469" alt="2017-08-10 17_19_25-add-ons manager - nightly" src="https://user-images.githubusercontent.com/208340/29174833-2b149326-7df0-11e7-9a77-8260d0162645.png">

**Comment by FoxBJK** [comment]
Yeah, noticed that the second time around. An authentication prompt appeared when I saved the URL without "/transmission/", so I didn't think the URL was the problem.

Add an idiot-proof error for dummies like me so that you can't save unless you have "/transmission/" in the Server URL :-)
