### ISSUE TITLE
Feature request - open/mount specified directory

### ISSUE THREAD

**Issue by unknowledgeable** [myfreeweb/transmitter#27]
It would be great to have an option to open a specified directory from the extension.

i.e. A button that opens a downloads folder (like the native "Show All Downloads" in firefox but for a different directory) or double click on a download to open it's own sub-directory.

I realise this extension is intended for people using transmission-remote so what I think would be most useful is if there were a way it could open or even mount an Avahi/SMB/SSHFS directory. Is this possible?

Many thanks

**Comment by valpackett** [comment]
No, I can't think of an easy way to open a remote directory from a browser. That would probably require a [native app](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Native_messaging) and that's way out of scope for this extension.

**Comment by unknowledgeable** [comment]
Fair enough! Great extension anyway, thanks for the good work!
