### ISSUE TITLE
Adding of "web" to end of server URL

### ISSUE THREAD

**Issue by wookienz** [myfreeweb/transmitter#28]
Adding in server URL without trailing /, plugin auto adds on "web" to end then making incorrect url

ie server: "https://transmission.example.org" becomes "https://transmission.example.orgweb"

adding in trailing / doesnt add web to end.

**Comment by valpackett** [comment]
You are not supposed to enter the URL without a trailing slash.

The form text says:

> …/transmission/, without /web/ or /rpc/ at the end
