### ISSUE TITLE
Don't have access to location chooser

### ISSUE THREAD

**Issue by deafmute1** [myfreeweb/transmitter#36]
Don't have access to the location choose as added in PR #26.

Using v1.1.1 in firefox, downloaded from firefox store:
<img width="680" alt="Screenshot 2024-01-23 at 15 33 46" src="https://github.com/valpackett/transmitter/assets/32427188/8cd884b7-1ab9-4dfe-b17b-000033eba531">

This is what my settings looks like:
<img width="659" alt="Screenshot 2024-01-23 at 15 35 04" src="https://github.com/valpackett/transmitter/assets/32427188/0eed546e-e893-4fc6-ace9-f7669073f7c3">

**Comment by valpackett** [comment]
Oof, I hadn't made a release in quite a while. Submitted 1.2.0 now to AMO.
