### ISSUE TITLE
download with transmission link not working

### ISSUE THREAD

**Issue by midros** [myfreeweb/transmitter#7]
as the title says, everything works ok but when I right click on the link to download a torrent file, and select "download with transmission remote" nothing happens

**Comment by valpackett** [comment]
It shouldn't display anything, check the transmission UI to see if the torrent is added.

**Comment by midros** [comment]
this is exactly what I mean. the torrent is not added.

**Comment by valpackett** [comment]
Does the link work when you add it manually in the web UI?

**Comment by midros** [comment]
If I copy - paste it in the web UI it is not added (for some reason but I have never tried this before).
If I save it and then add it manually, it is added.
If I add the link using the "Transmission easy client" add-on it is also added.

**Comment by valpackett** [comment]
Yeah, my extension does literally the same thing as the web UI.

Looks like that link requires your session cookies or something.

**Comment by valpackett** [comment]
Version 1.1.0 now supports private torrents!
