### ISSUE TITLE
Not work for private torrents

### ISSUE THREAD

**Issue by Alexey71** [myfreeweb/transmitter#8]
try submitting the link of the torrent to the web interface of transmission but this doesnt work for private sites that need a session for the torrent file to be downloaded.

**Comment by valpackett** [comment]
Yes, this is not supported in Transmission, I can't do anything about this. You have to click to open the web interface and upload the torrent file to Transmission.

**Comment by Alexey71** [comment]
Hm. How works other extension? https://addons.mozilla.org/ru/firefox/addon/torrent-to-web/

**Comment by valpackett** [comment]
Oh, they download the torrent in the browser and reupload to Transmission…

**Comment by Alexey71** [comment]
Can you do this in your extension? Your extension is the best of all ...

**Comment by valpackett** [comment]
Yeah, I'll try that soon

**Comment by valpackett** [comment]
Please test the current git master version (Clone or download → Download ZIP, extract, go to `about:debugging` in Firefox, click Load Temporary Addon, select `manifest.json` in the extracted folder), should work now

**Comment by Alexey71** [comment]
Work. Please upload to addons.mozilla.org

**Comment by valpackett** [comment]
Uploaded (and approved already, wow that was fast!)
